// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: esp32_gui

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void SpinAndLargen_Animation(lv_obj_t * TargetObject, int delay);
void LargeBtn_Animation(lv_obj_t * TargetObject, int delay);
void MoveColorToCenter_Animation(lv_obj_t * TargetObject, int delay);
void MoveSettingsToCenter_Animation(lv_obj_t * TargetObject, int delay);
void HideBtn_Animation(lv_obj_t * TargetObject, int delay);
void ShowBtn_Animation(lv_obj_t * TargetObject, int delay);
lv_obj_t * ui_Home_Scr;
void ui_event_Color_Btn_Home(lv_event_t * e);
lv_obj_t * ui_Color_Btn_Home;
lv_obj_t * ui_Colorwheel_Home;
lv_obj_t * ui_BL_logo_Home;
lv_obj_t * ui_Dark_Mode_Label;
void ui_event_Dark_Mode_Switch(lv_event_t * e);
lv_obj_t * ui_Dark_Mode_Switch;
void ui_event_Settings_Btn_Home(lv_event_t * e);
lv_obj_t * ui_Settings_Btn_Home;
lv_obj_t * ui_Settings_Icon_Home;
lv_obj_t * ui_Color_Scr;
void ui_event_Dark_Mode_Switch_Color(lv_event_t * e);
lv_obj_t * ui_Dark_Mode_Switch_Color;
lv_obj_t * ui_Dark_Mode_Label_Color;
void ui_event_Home_Btn_Color(lv_event_t * e);
lv_obj_t * ui_Home_Btn_Color;
lv_obj_t * ui_Home_Img_C;
lv_obj_t * ui_BL_logo_Color;
lv_obj_t * ui_Colorwheel;
lv_obj_t * ui_LED_color_panel;
lv_obj_t * ui_LED_color_label;
lv_obj_t * ui_Settings_Scr;
void ui_event_Dark_Mode_Switch_Sett(lv_event_t * e);
lv_obj_t * ui_Dark_Mode_Switch_Sett;
lv_obj_t * ui_Dark_Mode_Label_Sett;
void ui_event_Home_Btn_Sett(lv_event_t * e);
lv_obj_t * ui_Home_Btn_Sett;
lv_obj_t * ui_Home_Img_S;
lv_obj_t * ui_BL_logo_Sett;
lv_obj_t * ui_Settings_scroll_panel;
lv_obj_t * ui_Checkbox_Sett;
lv_obj_t * ui_Dropdown_Sett;
lv_obj_t * ui_Roller_Sett;
lv_obj_t * ui_Slider1_Sett;
void ui_event_Text_area(lv_event_t * e);
lv_obj_t * ui_Text_area;
lv_obj_t * ui_Arc_Sett;
lv_obj_t * ui_Slider2_Sett;
void ui_event_Keyboard_Sett(lv_event_t * e);
lv_obj_t * ui_Keyboard_Sett;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void SpinAndLargen_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle);
    lv_anim_set_values(&PropertyAnimation_0, 0, 3600);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_angle);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 1000);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_image_zoom);
    lv_anim_set_values(&PropertyAnimation_1, 120, 370);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_start(&PropertyAnimation_1);
    ui_anim_user_data_t * PropertyAnimation_2_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_2_user_data->target = TargetObject;
    PropertyAnimation_2_user_data->val = -1;
    lv_anim_t PropertyAnimation_2;
    lv_anim_init(&PropertyAnimation_2);
    lv_anim_set_time(&PropertyAnimation_2, 1000);
    lv_anim_set_user_data(&PropertyAnimation_2, PropertyAnimation_2_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_2, _ui_anim_callback_set_image_zoom);
    lv_anim_set_values(&PropertyAnimation_2, 370, 120);
    lv_anim_set_path_cb(&PropertyAnimation_2, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_2, delay + 2000);
    lv_anim_set_deleted_cb(&PropertyAnimation_2, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_2, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_2, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_2, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_2, 0);
    lv_anim_set_early_apply(&PropertyAnimation_2, false);
    lv_anim_start(&PropertyAnimation_2);

}
void LargeBtn_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_width);
    lv_anim_set_values(&PropertyAnimation_0, 75, 320);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 1000);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_height);
    lv_anim_set_values(&PropertyAnimation_1, 68, 240);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_start(&PropertyAnimation_1);
    ui_anim_user_data_t * PropertyAnimation_2_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_2_user_data->target = TargetObject;
    PropertyAnimation_2_user_data->val = -1;
    lv_anim_t PropertyAnimation_2;
    lv_anim_init(&PropertyAnimation_2);
    lv_anim_set_time(&PropertyAnimation_2, 1000);
    lv_anim_set_user_data(&PropertyAnimation_2, PropertyAnimation_2_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_2, _ui_anim_callback_set_width);
    lv_anim_set_values(&PropertyAnimation_2, 320, 75);
    lv_anim_set_path_cb(&PropertyAnimation_2, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_2, delay + 2000);
    lv_anim_set_deleted_cb(&PropertyAnimation_2, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_2, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_2, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_2, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_2, 0);
    lv_anim_set_early_apply(&PropertyAnimation_2, false);
    lv_anim_start(&PropertyAnimation_2);
    ui_anim_user_data_t * PropertyAnimation_3_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_3_user_data->target = TargetObject;
    PropertyAnimation_3_user_data->val = -1;
    lv_anim_t PropertyAnimation_3;
    lv_anim_init(&PropertyAnimation_3);
    lv_anim_set_time(&PropertyAnimation_3, 1000);
    lv_anim_set_user_data(&PropertyAnimation_3, PropertyAnimation_3_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_3, _ui_anim_callback_set_height);
    lv_anim_set_values(&PropertyAnimation_3, 240, 68);
    lv_anim_set_path_cb(&PropertyAnimation_3, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_3, delay + 2000);
    lv_anim_set_deleted_cb(&PropertyAnimation_3, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_3, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_3, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_3, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_3, 0);
    lv_anim_set_early_apply(&PropertyAnimation_3, false);
    lv_anim_start(&PropertyAnimation_3);

}
void MoveColorToCenter_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, 0, 64);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_x);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 1000);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_1, 0, -64);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 2000);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_start(&PropertyAnimation_1);

}
void MoveSettingsToCenter_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, 64, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 1000);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_1, 0, 64);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 2000);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_start(&PropertyAnimation_1);

}
void HideBtn_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 255, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void ShowBtn_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Color_Btn_Home(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        SpinAndLargen_Animation(ui_Colorwheel_Home, 0);
        LargeBtn_Animation(ui_Color_Btn_Home, 0);
        MoveColorToCenter_Animation(ui_Color_Btn_Home, 0);
        HideBtn_Animation(ui_Settings_Btn_Home, 0);
        ShowBtn_Animation(ui_Settings_Btn_Home, 1200);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_Color_Scr, LV_SCR_LOAD_ANIM_FADE_ON, 500, 1000);
    }
}
void ui_event_Dark_Mode_Switch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        dark_mode_on(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        dark_mode_off(e);
    }
}
void ui_event_Settings_Btn_Home(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        SpinAndLargen_Animation(ui_Settings_Icon_Home, 0);
        LargeBtn_Animation(ui_Settings_Btn_Home, 0);
        MoveSettingsToCenter_Animation(ui_Settings_Btn_Home, 0);
        HideBtn_Animation(ui_Color_Btn_Home, 0);
        ShowBtn_Animation(ui_Color_Btn_Home, 1200);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_Settings_Scr, LV_SCR_LOAD_ANIM_FADE_ON, 500, 1000);
    }
}
void ui_event_Dark_Mode_Switch_Color(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        dark_mode_on(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        dark_mode_off(e);
    }
}
void ui_event_Home_Btn_Color(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_Home_Scr, LV_SCR_LOAD_ANIM_OVER_RIGHT, 500, 0);
    }
}
void ui_event_Dark_Mode_Switch_Sett(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        dark_mode_on(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        dark_mode_off(e);
    }
}
void ui_event_Home_Btn_Sett(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_Home_Scr, LV_SCR_LOAD_ANIM_OVER_RIGHT, 500, 0);
    }
}
void ui_event_Text_area(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard_Sett, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_keyboard_set_target(ui_Keyboard_Sett,  ui_Text_area);
    }
}
void ui_event_Keyboard_Sett(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_Keyboard_Sett, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

///////////////////// SCREENS ////////////////////
void ui_Home_Scr_screen_init(void)
{
    ui_Home_Scr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Home_Scr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Home_Scr, lv_color_hex(0x111111), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Home_Scr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Color_Btn_Home = lv_btn_create(ui_Home_Scr);
    lv_obj_set_width(ui_Color_Btn_Home, 75);
    lv_obj_set_height(ui_Color_Btn_Home, 68);
    lv_obj_set_x(ui_Color_Btn_Home, -64);
    lv_obj_set_y(ui_Color_Btn_Home, 0);
    lv_obj_set_align(ui_Color_Btn_Home, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Color_Btn_Home, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Color_Btn_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Color_Btn_Home, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Color_Btn_Home, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Colorwheel_Home = lv_img_create(ui_Color_Btn_Home);
    lv_img_set_src(ui_Colorwheel_Home, &ui_img_colorwheel_icon_png);
    lv_obj_set_width(ui_Colorwheel_Home, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Colorwheel_Home, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Colorwheel_Home, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Colorwheel_Home, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Colorwheel_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Colorwheel_Home, 120);

    ui_BL_logo_Home = lv_img_create(ui_Home_Scr);
    lv_img_set_src(ui_BL_logo_Home, &ui_img_bl_logo_symbol_png);
    lv_obj_set_width(ui_BL_logo_Home, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BL_logo_Home, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BL_logo_Home, 139);
    lv_obj_set_y(ui_BL_logo_Home, -101);
    lv_obj_set_align(ui_BL_logo_Home, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BL_logo_Home, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BL_logo_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_BL_logo_Home, 50);

    ui_Dark_Mode_Label = lv_label_create(ui_Home_Scr);
    lv_obj_set_width(ui_Dark_Mode_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Dark_Mode_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dark_Mode_Label, 76);
    lv_obj_set_y(ui_Dark_Mode_Label, 107);
    lv_obj_set_align(ui_Dark_Mode_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Dark_Mode_Label, "Dark mode");
    lv_obj_set_style_text_color(ui_Dark_Mode_Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dark_Mode_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Dark_Mode_Label, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_Dark_Mode_Label, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Dark_Mode_Switch = lv_switch_create(ui_Home_Scr);
    lv_obj_set_width(ui_Dark_Mode_Switch, 32);
    lv_obj_set_height(ui_Dark_Mode_Switch, 15);
    lv_obj_set_x(ui_Dark_Mode_Switch, 139);
    lv_obj_set_y(ui_Dark_Mode_Switch, 107);
    lv_obj_set_align(ui_Dark_Mode_Switch, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Dark_Mode_Switch, LV_STATE_CHECKED);       /// States

    lv_obj_set_style_bg_color(ui_Dark_Mode_Switch, lv_color_hex(0x6AC6A4), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Dark_Mode_Switch, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_Settings_Btn_Home = lv_btn_create(ui_Home_Scr);
    lv_obj_set_width(ui_Settings_Btn_Home, 75);
    lv_obj_set_height(ui_Settings_Btn_Home, 68);
    lv_obj_set_y(ui_Settings_Btn_Home, -1);
    lv_obj_set_x(ui_Settings_Btn_Home, lv_pct(20));
    lv_obj_set_align(ui_Settings_Btn_Home, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Settings_Btn_Home, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Settings_Btn_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Settings_Btn_Home, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settings_Btn_Home, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Settings_Icon_Home = lv_img_create(ui_Settings_Btn_Home);
    lv_img_set_src(ui_Settings_Icon_Home, &ui_img_settings_icon_png);
    lv_obj_set_width(ui_Settings_Icon_Home, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Settings_Icon_Home, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Settings_Icon_Home, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Settings_Icon_Home, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Settings_Icon_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Settings_Icon_Home, 120);
    lv_obj_set_style_bg_color(ui_Settings_Icon_Home, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settings_Icon_Home, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Color_Btn_Home, ui_event_Color_Btn_Home, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dark_Mode_Switch, ui_event_Dark_Mode_Switch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Settings_Btn_Home, ui_event_Settings_Btn_Home, LV_EVENT_ALL, NULL);

}
void ui_Color_Scr_screen_init(void)
{
    ui_Color_Scr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Color_Scr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Color_Scr, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Color_Scr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dark_Mode_Switch_Color = lv_switch_create(ui_Color_Scr);
    lv_obj_set_width(ui_Dark_Mode_Switch_Color, 32);
    lv_obj_set_height(ui_Dark_Mode_Switch_Color, 15);
    lv_obj_set_x(ui_Dark_Mode_Switch_Color, 139);
    lv_obj_set_y(ui_Dark_Mode_Switch_Color, 107);
    lv_obj_set_align(ui_Dark_Mode_Switch_Color, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Dark_Mode_Switch_Color, LV_STATE_CHECKED);       /// States

    lv_obj_set_style_bg_color(ui_Dark_Mode_Switch_Color, lv_color_hex(0x6AC6A4), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Dark_Mode_Switch_Color, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_Dark_Mode_Label_Color = lv_label_create(ui_Color_Scr);
    lv_obj_set_width(ui_Dark_Mode_Label_Color, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Dark_Mode_Label_Color, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dark_Mode_Label_Color, 76);
    lv_obj_set_y(ui_Dark_Mode_Label_Color, 107);
    lv_obj_set_align(ui_Dark_Mode_Label_Color, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Dark_Mode_Label_Color, "Dark mode");
    lv_obj_set_style_text_color(ui_Dark_Mode_Label_Color, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dark_Mode_Label_Color, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Dark_Mode_Label_Color, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_Dark_Mode_Label_Color, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Home_Btn_Color = lv_btn_create(ui_Color_Scr);
    lv_obj_set_width(ui_Home_Btn_Color, 36);
    lv_obj_set_height(ui_Home_Btn_Color, 31);
    lv_obj_set_x(ui_Home_Btn_Color, -133);
    lv_obj_set_y(ui_Home_Btn_Color, 94);
    lv_obj_set_align(ui_Home_Btn_Color, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Home_Btn_Color, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Home_Btn_Color, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Home_Btn_Color, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Home_Btn_Color, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Home_Img_C = lv_img_create(ui_Home_Btn_Color);
    lv_img_set_src(ui_Home_Img_C, &ui_img_home_icon_png);
    lv_obj_set_width(ui_Home_Img_C, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Home_Img_C, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Home_Img_C, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Home_Img_C, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Home_Img_C, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Home_Img_C, 50);

    ui_BL_logo_Color = lv_img_create(ui_Color_Scr);
    lv_img_set_src(ui_BL_logo_Color, &ui_img_bl_logo_symbol_png);
    lv_obj_set_width(ui_BL_logo_Color, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BL_logo_Color, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BL_logo_Color, 139);
    lv_obj_set_y(ui_BL_logo_Color, -101);
    lv_obj_set_align(ui_BL_logo_Color, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BL_logo_Color, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BL_logo_Color, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_BL_logo_Color, 50);

    ui_Colorwheel = lv_colorwheel_create(ui_Color_Scr, true);
    lv_obj_set_width(ui_Colorwheel, 150);
    lv_obj_set_height(ui_Colorwheel, 150);
    lv_obj_set_x(ui_Colorwheel, 60);
    lv_obj_set_y(ui_Colorwheel, -5);
    lv_obj_set_align(ui_Colorwheel, LV_ALIGN_CENTER);

    ui_LED_color_panel = lv_obj_create(ui_Color_Scr);
    lv_obj_set_width(ui_LED_color_panel, 139);
    lv_obj_set_height(ui_LED_color_panel, 31);
    lv_obj_set_x(ui_LED_color_panel, -83);
    lv_obj_set_y(ui_LED_color_panel, -75);
    lv_obj_set_align(ui_LED_color_panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LED_color_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LED_color_panel, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LED_color_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LED_color_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LED_color_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LED_color_label = lv_label_create(ui_LED_color_panel);
    lv_obj_set_width(ui_LED_color_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LED_color_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LED_color_label, 2);
    lv_obj_set_y(ui_LED_color_label, 1);
    lv_obj_set_align(ui_LED_color_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LED_color_label, "LED color");
    lv_obj_set_style_text_font(ui_LED_color_label, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Dark_Mode_Switch_Color, ui_event_Dark_Mode_Switch_Color, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Home_Btn_Color, ui_event_Home_Btn_Color, LV_EVENT_ALL, NULL);

}
void ui_Settings_Scr_screen_init(void)
{
    ui_Settings_Scr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Settings_Scr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Settings_Scr, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settings_Scr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dark_Mode_Switch_Sett = lv_switch_create(ui_Settings_Scr);
    lv_obj_set_width(ui_Dark_Mode_Switch_Sett, 32);
    lv_obj_set_height(ui_Dark_Mode_Switch_Sett, 15);
    lv_obj_set_x(ui_Dark_Mode_Switch_Sett, 139);
    lv_obj_set_y(ui_Dark_Mode_Switch_Sett, 107);
    lv_obj_set_align(ui_Dark_Mode_Switch_Sett, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Dark_Mode_Switch_Sett, LV_STATE_CHECKED);       /// States

    lv_obj_set_style_bg_color(ui_Dark_Mode_Switch_Sett, lv_color_hex(0x6AC6A4), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Dark_Mode_Switch_Sett, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_Dark_Mode_Label_Sett = lv_label_create(ui_Settings_Scr);
    lv_obj_set_width(ui_Dark_Mode_Label_Sett, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Dark_Mode_Label_Sett, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dark_Mode_Label_Sett, 76);
    lv_obj_set_y(ui_Dark_Mode_Label_Sett, 107);
    lv_obj_set_align(ui_Dark_Mode_Label_Sett, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Dark_Mode_Label_Sett, "Dark mode");
    lv_obj_set_style_text_color(ui_Dark_Mode_Label_Sett, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dark_Mode_Label_Sett, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Dark_Mode_Label_Sett, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_Dark_Mode_Label_Sett, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Home_Btn_Sett = lv_btn_create(ui_Settings_Scr);
    lv_obj_set_width(ui_Home_Btn_Sett, 36);
    lv_obj_set_height(ui_Home_Btn_Sett, 31);
    lv_obj_set_x(ui_Home_Btn_Sett, -133);
    lv_obj_set_y(ui_Home_Btn_Sett, 94);
    lv_obj_set_align(ui_Home_Btn_Sett, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Home_Btn_Sett, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Home_Btn_Sett, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Home_Btn_Sett, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Home_Btn_Sett, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Home_Img_S = lv_img_create(ui_Home_Btn_Sett);
    lv_img_set_src(ui_Home_Img_S, &ui_img_home_icon_png);
    lv_obj_set_width(ui_Home_Img_S, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Home_Img_S, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Home_Img_S, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Home_Img_S, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Home_Img_S, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Home_Img_S, 50);

    ui_BL_logo_Sett = lv_img_create(ui_Settings_Scr);
    lv_img_set_src(ui_BL_logo_Sett, &ui_img_bl_logo_symbol_png);
    lv_obj_set_width(ui_BL_logo_Sett, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BL_logo_Sett, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BL_logo_Sett, 139);
    lv_obj_set_y(ui_BL_logo_Sett, -101);
    lv_obj_set_align(ui_BL_logo_Sett, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BL_logo_Sett, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BL_logo_Sett, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_BL_logo_Sett, 50);

    ui_Settings_scroll_panel = lv_obj_create(ui_Settings_Scr);
    lv_obj_set_width(ui_Settings_scroll_panel, 304);
    lv_obj_set_height(ui_Settings_scroll_panel, 153);
    lv_obj_set_align(ui_Settings_scroll_panel, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Settings_scroll_panel, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settings_scroll_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Settings_scroll_panel, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Settings_scroll_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Checkbox_Sett = lv_checkbox_create(ui_Settings_scroll_panel);
    lv_checkbox_set_text(ui_Checkbox_Sett, "This is a checkbox");
    lv_obj_set_width(ui_Checkbox_Sett, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox_Sett, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Checkbox_Sett, -60);
    lv_obj_set_y(ui_Checkbox_Sett, -53);
    lv_obj_set_align(ui_Checkbox_Sett, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox_Sett, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_Checkbox_Sett, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Checkbox_Sett, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_Checkbox_Sett, lv_color_hex(0x6AC6A4), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Checkbox_Sett, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Checkbox_Sett, lv_color_hex(0x6AC6A4), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Checkbox_Sett, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_Dropdown_Sett = lv_dropdown_create(ui_Settings_scroll_panel);
    lv_dropdown_set_options(ui_Dropdown_Sett, "Byte-Lab\nByteLab\nByte Lab\nBL");
    lv_obj_set_width(ui_Dropdown_Sett, 262);
    lv_obj_set_height(ui_Dropdown_Sett, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown_Sett, -8);
    lv_obj_set_y(ui_Dropdown_Sett, -15);
    lv_obj_set_align(ui_Dropdown_Sett, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown_Sett, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_Dropdown_Sett, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown_Sett, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dropdown_Sett, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dropdown_Sett, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roller_Sett = lv_roller_create(ui_Settings_scroll_panel);
    lv_roller_set_options(ui_Roller_Sett, "Byte-Lab\nByteLab\nByte Lab\nBL", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_Roller_Sett, 100);
    lv_obj_set_width(ui_Roller_Sett, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller_Sett, -93);
    lv_obj_set_y(ui_Roller_Sett, 64);
    lv_obj_set_align(ui_Roller_Sett, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_Roller_Sett, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Roller_Sett, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller_Sett, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller_Sett, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Roller_Sett, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Roller_Sett, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller_Sett, lv_color_hex(0x6AC6A4), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller_Sett, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Slider1_Sett = lv_slider_create(ui_Settings_scroll_panel);
    lv_slider_set_range(ui_Slider1_Sett, 0, 20);
    lv_slider_set_value(ui_Slider1_Sett, 11, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1_Sett) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1_Sett, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1_Sett, 150);
    lv_obj_set_height(ui_Slider1_Sett, 10);
    lv_obj_set_x(ui_Slider1_Sett, 45);
    lv_obj_set_y(ui_Slider1_Sett, 25);
    lv_obj_set_align(ui_Slider1_Sett, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Slider1_Sett, lv_color_hex(0xA1AAAD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1_Sett, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider1_Sett, lv_color_hex(0x6AC6A4), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1_Sett, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider1_Sett, lv_color_hex(0x6AC6A4), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1_Sett, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Text_area = lv_textarea_create(ui_Settings_scroll_panel);
    lv_obj_set_width(ui_Text_area, 167);
    lv_obj_set_height(ui_Text_area, LV_SIZE_CONTENT);    /// 75
    lv_obj_set_x(ui_Text_area, -56);
    lv_obj_set_y(ui_Text_area, 145);
    lv_obj_set_align(ui_Text_area, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_Text_area, "Type text here...");
    lv_textarea_set_one_line(ui_Text_area, true);

    ui_Arc_Sett = lv_arc_create(ui_Settings_scroll_panel);
    lv_obj_set_width(ui_Arc_Sett, 89);
    lv_obj_set_height(ui_Arc_Sett, 86);
    lv_obj_set_x(ui_Arc_Sett, 81);
    lv_obj_set_y(ui_Arc_Sett, 132);
    lv_obj_set_align(ui_Arc_Sett, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc_Sett, 89);
    lv_obj_set_style_arc_color(ui_Arc_Sett, lv_color_hex(0xA4AAAC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc_Sett, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Arc_Sett, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Arc_Sett, lv_color_hex(0x6AC6A4), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc_Sett, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_Arc_Sett, lv_color_hex(0x6AC6A4), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc_Sett, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc_Sett, lv_color_hex(0x6AC6A4), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc_Sett, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Slider2_Sett = lv_slider_create(ui_Settings_scroll_panel);
    lv_slider_set_value(ui_Slider2_Sett, 11, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2_Sett) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2_Sett, 1,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2_Sett, 150);
    lv_obj_set_height(ui_Slider2_Sett, 10);
    lv_obj_set_x(ui_Slider2_Sett, 45);
    lv_obj_set_y(ui_Slider2_Sett, 66);
    lv_obj_set_align(ui_Slider2_Sett, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Slider2_Sett, lv_color_hex(0xA4AAAC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2_Sett, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider2_Sett, lv_color_hex(0x6AC6A4), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2_Sett, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider2_Sett, lv_color_hex(0x6AC6A4), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2_Sett, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Keyboard_Sett = lv_keyboard_create(ui_Settings_scroll_panel);
    lv_obj_set_width(ui_Keyboard_Sett, 273);
    lv_obj_set_height(ui_Keyboard_Sett, 119);
    lv_obj_set_x(ui_Keyboard_Sett, 0);
    lv_obj_set_y(ui_Keyboard_Sett, 233);
    lv_obj_set_align(ui_Keyboard_Sett, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard_Sett, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_Dark_Mode_Switch_Sett, ui_event_Dark_Mode_Switch_Sett, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Home_Btn_Sett, ui_event_Home_Btn_Sett, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Text_area, ui_event_Text_area, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard_Sett, ui_Text_area);
    lv_obj_add_event_cb(ui_Keyboard_Sett, ui_event_Keyboard_Sett, LV_EVENT_ALL, NULL);

}

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Home_Scr_screen_init();
    ui_Color_Scr_screen_init();
    ui_Settings_Scr_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Home_Scr);
}
