// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: esp32_gui

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void dark_mode_on(lv_event_t *p_evt);
void dark_mode_off(lv_event_t *p_evt);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
